name: Newman API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman + HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman Collection
        run: |
          newman run Postman/Day2.postman_collection.json -r cli,htmlextra
